import React from 'react';
import {
  Award,
  Sparkles,
  Users,
  Store,
  Navigation,
  School,
  Building2,
  Calendar,
  Layers,
  ArrowRight,
  Info,
  Clock,
  Database,
  ExternalLink,
} from 'lucide-react';

import { api } from '../services/api';

const BAND_COLORS = {
  Excellent: { bg: 'bg-emerald-100', text: 'text-emerald-800', border: 'border-emerald-300' },
  Good: { bg: 'bg-blue-100', text: 'text-blue-800', border: 'border-blue-300' },
  Fair: { bg: 'bg-amber-100', text: 'text-amber-800', border: 'border-amber-300' },
  Poor: { bg: 'bg-red-100', text: 'text-red-800', border: 'border-red-300' },
};

export default function ReportView({ report, onAssignScouting, onCompareClick }) {
  const [requestingStudy, setRequestingStudy] = React.useState(false);
  const [studyResult, setStudyResult] = React.useState(null);

  if (!report) return null;

  const score = report.score ?? 0;
  const band = report.band || 'Good';
  const bandStyle = BAND_COLORS[band] || BAND_COLORS.Good;
  const profile = report.area_profile || {};
  const breakdown = report.breakdown || [];
  const hotspots = report.hotspots || [];
  const dataVersions = report.data_versions || [];

  const handleRequestStudy = async () => {
    try {
      setRequestingStudy(true);
      setStudyResult(null);
      const res = await api.createStudy({
        target_type: 'area',
        report_id: report.id,
        radius_m: 1000.0,
      });
      if (res.reused) {
        setStudyResult({
          reused: true,
          message: res.reuse_message || `Reused completed study #${res.id}`,
        });
      } else {
        setStudyResult({
          reused: false,
          message: `Catchment study #${res.id} requested for this area report. Dispatched to Survey Operations.`,
        });
      }
    } catch (err) {
      setStudyResult({
        error: true,
        message: err.message || 'Failed to request catchment study.',
      });
    } finally {
      setRequestingStudy(false);
    }
  };


  return (
    <div className="space-y-6">
      {/* Top Overview Card */}
      <div className="bg-white rounded-3xl p-6 sm:p-8 shadow-sm border border-gray-200">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-6">
          {/* Title & Metadata */}
          <div className="space-y-2 flex-1">
            <div className="flex items-center space-x-2">
              <span className={`px-3 py-1 rounded-full text-xs font-bold border ${bandStyle.bg} ${bandStyle.text} ${bandStyle.border}`}>
                {band} Expansion Fitness
              </span>
              <span className="text-xs text-gray-500">
                {report.cell_ids?.length || 1} Grid Cell{report.cell_ids?.length > 1 ? 's' : ''} (
                {((report.cell_ids?.length || 1) * 0.25).toFixed(2)} km²)
              </span>
            </div>
            <h1 className="text-2xl sm:text-3xl font-extrabold text-gray-900 tracking-tight">
              {report.name}
            </h1>
            <p className="text-xs sm:text-sm text-gray-500">
              Generated by <span className="font-semibold text-brand-purple">{report.created_by}</span> on{' '}
              {report.created_at ? new Date(report.created_at).toLocaleString() : 'Recent'}
            </p>

            <div className="pt-2 flex flex-wrap items-center gap-2">
              <button
                id="btn-report-request-study"
                onClick={handleRequestStudy}
                disabled={requestingStudy}
                className="px-3.5 py-1.5 bg-brand-yellow hover:bg-yellow-400 text-brand-purple font-black text-xs rounded-xl shadow-sm transition flex items-center space-x-1.5 disabled:opacity-50"
              >
                <Sparkles className={`w-3.5 h-3.5 ${requestingStudy ? 'animate-spin' : ''}`} />
                <span>{requestingStudy ? 'Checking 6-Mo Reuse...' : 'Request Catchment Study'}</span>
              </button>
            </div>

            {studyResult && (
              <div className={`mt-2 p-3 rounded-xl border text-xs font-semibold ${
                studyResult.error
                  ? 'bg-red-50 border-red-200 text-red-700'
                  : studyResult.reused
                  ? 'bg-amber-50 border-amber-300 text-amber-900'
                  : 'bg-purple-50 border-purple-200 text-purple-900'
              }`}>
                {studyResult.reused && <span className="font-black mr-1">⚡ 6-Month Reuse:</span>}
                <span>{studyResult.message}</span>
              </div>
            )}
          </div>


          {/* Score Gauge */}
          <div className="flex items-center space-x-5 bg-purple-50/60 p-4 rounded-2xl border border-purple-100 self-start md:self-auto">
            <div className="relative w-24 h-24 flex items-center justify-center">
              <svg className="w-24 h-24 transform -rotate-90" viewBox="0 0 36 36">
                <path
                  className="text-purple-200"
                  strokeWidth="3.5"
                  stroke="currentColor"
                  fill="none"
                  d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                />
                <path
                  className="text-brand-purple transition-all duration-1000 ease-out"
                  strokeDasharray={`${score}, 100`}
                  strokeWidth="3.5"
                  strokeLinecap="round"
                  stroke="currentColor"
                  fill="none"
                  d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                />
              </svg>
              <div className="absolute flex flex-col items-center">
                <span className="text-2xl font-black text-brand-purple leading-none">{score}</span>
                <span className="text-[10px] font-bold text-gray-500 uppercase tracking-wider">/ 100</span>
              </div>
            </div>
            <div>
              <div className="text-xs font-semibold text-gray-500 uppercase tracking-wider">Fitness Index</div>
              <div className="text-lg font-black text-gray-900">{band} Viability</div>
              {onCompareClick && (
                <button
                  onClick={onCompareClick}
                  className="mt-2 text-xs font-bold text-brand-purple hover:underline flex items-center space-x-1"
                >
                  <span>Compare report</span>
                  <ExternalLink className="w-3 h-3" />
                </button>
              )}
            </div>
          </div>
        </div>

        {/* AI Narrative Section */}
        <div className="mt-6 pt-6 border-t border-gray-100">
          <div className="flex items-center justify-between mb-2">
            <div className="flex items-center space-x-2">
              <Sparkles className="w-4 h-4 text-brand-purple" />
              <h3 className="text-sm font-bold text-gray-900">Expansion Intelligence Narrative</h3>
            </div>
            <span className="px-2.5 py-0.5 rounded-full text-[11px] font-bold bg-purple-100 text-brand-purple border border-purple-200">
              {report.summary_source === 'llm' ? 'AI-generated from computed data' : 'Deterministic Template Summary'}
            </span>
          </div>
          <div className="bg-slate-50 p-4 rounded-xl border border-gray-200/80 text-xs sm:text-sm text-gray-700 leading-relaxed font-normal">
            {report.summary}
          </div>
        </div>
      </div>

      {/* Area Profile Stats */}
      <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-3 sm:gap-4">
        <div className="bg-white p-4 rounded-2xl border border-gray-200 shadow-sm space-y-1">
          <div className="flex items-center justify-between text-gray-500 text-xs">
            <span>Est. Population</span>
            <Users className="w-3.5 h-3.5 text-brand-purple" />
          </div>
          <div className="text-xl font-black text-gray-900">
            {profile.est_population ? Number(profile.est_population).toLocaleString() : '0'}
          </div>
          <span className="inline-block px-1.5 py-0.5 rounded text-[10px] font-semibold bg-orange-100 text-orange-700">
            Mock data (×4.5)
          </span>
        </div>

        <div className="bg-white p-4 rounded-2xl border border-gray-200 shadow-sm space-y-1">
          <div className="flex items-center justify-between text-gray-500 text-xs">
            <span>Supermarkets</span>
            <Store className="w-3.5 h-3.5 text-brand-purple" />
          </div>
          <div className="text-xl font-black text-gray-900">{profile.supermarkets ?? 0}</div>
          <span className="text-[11px] text-gray-500">Direct competitors</span>
        </div>

        <div className="bg-white p-4 rounded-2xl border border-gray-200 shadow-sm space-y-1">
          <div className="flex items-center justify-between text-gray-500 text-xs">
            <span>Local Groceries</span>
            <Store className="w-3.5 h-3.5 text-brand-purple" />
          </div>
          <div className="text-xl font-black text-gray-900">{profile.grocery_stores ?? 0}</div>
          <span className="text-[11px] text-gray-500">Kirana & daily stores</span>
        </div>

        <div className="bg-white p-4 rounded-2xl border border-gray-200 shadow-sm space-y-1">
          <div className="flex items-center justify-between text-gray-500 text-xs">
            <span>Civic Anchors</span>
            <School className="w-3.5 h-3.5 text-brand-purple" />
          </div>
          <div className="text-xl font-black text-gray-900">
            {(profile.schools || 0) + (profile.hospitals || 0)}
          </div>
          <span className="text-[11px] text-gray-500">Schools & Hospitals</span>
        </div>

        <div className="bg-white p-4 rounded-2xl border border-gray-200 shadow-sm space-y-1">
          <div className="flex items-center justify-between text-gray-500 text-xs">
            <span>Transit Stops</span>
            <Navigation className="w-3.5 h-3.5 text-brand-purple" />
          </div>
          <div className="text-xl font-black text-gray-900">
            {(profile.bus_stops || 0) + (profile.rail_stations || 0)}
          </div>
          <span className="text-[11px] text-gray-500">Bus & Metro nodes</span>
        </div>

        <div className="bg-white p-4 rounded-2xl border border-gray-200 shadow-sm space-y-1">
          <div className="flex items-center justify-between text-gray-500 text-xs">
            <span>Savomart Buffer</span>
            <Building2 className="w-3.5 h-3.5 text-brand-purple" />
          </div>
          <div className="text-xl font-black text-gray-900">
            {profile.nearest_savomart_dist_meters ? `${profile.nearest_savomart_dist_meters}m` : 'N/A'}
          </div>
          <span className="text-[11px] text-gray-500">&gt; 800m safe zone</span>
        </div>
      </div>

      {/* Factor Breakdown Bars */}
      <div className="bg-white rounded-3xl p-6 sm:p-8 shadow-sm border border-gray-200 space-y-5">
        <div>
          <h2 className="text-lg font-bold text-gray-900">Explainable Factor Breakdown</h2>
          <p className="text-xs text-gray-500 mt-0.5">
            Every score is deterministically calculated in Python: <span className="font-semibold text-gray-700">Normalised (0–1) × Weight = Points</span>.
          </p>
        </div>

        <div className="space-y-4">
          {breakdown.map((item, idx) => (
            <div key={idx} className="p-4 rounded-2xl bg-gray-50/70 border border-gray-200 space-y-2">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-1">
                <div className="flex items-center space-x-2">
                  <span className="text-sm font-bold text-gray-900">{item.name}</span>
                  {item.is_mock && (
                    <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-orange-100 text-orange-700">
                      Mock data
                    </span>
                  )}
                </div>
                <div className="text-xs font-semibold text-gray-600">
                  Raw: <span className="text-gray-900 font-bold">{item.raw_value}</span> {item.unit} |{' '}
                  <span className="text-brand-purple font-black">
                    {item.normalised} × {item.weight} = {item.points} pts
                  </span>
                </div>
              </div>

              {/* Progress bar */}
              <div className="w-full bg-gray-200 h-2.5 rounded-full overflow-hidden">
                <div
                  className="bg-brand-purple h-2.5 rounded-full transition-all duration-700"
                  style={{ width: `${Math.min(100, Math.max(0, item.normalised * 100))}%` }}
                ></div>
              </div>

              {/* Plain English "Why" */}
              <p className="text-xs text-gray-600 italic">
                <span className="font-semibold not-italic text-gray-700">Assessment:</span> {item.why}
              </p>
            </div>
          ))}
        </div>
      </div>

      {/* Hotspots Section */}
      <div className="bg-white rounded-3xl p-6 sm:p-8 shadow-sm border border-gray-200 space-y-4">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-lg font-bold text-gray-900 flex items-center space-x-2">
              <span className="w-5 h-5 rounded-full bg-brand-yellow flex items-center justify-center text-brand-purple font-black text-xs">
                #
              </span>
              <span>Identified Scouting Hotspots (Top {hotspots.length})</span>
            </h2>
            <p className="text-xs text-gray-500 mt-0.5">
              Specific 500m cells within the selection exhibiting optimal retail viability for new property scouting.
            </p>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {hotspots.map((hs, idx) => (
            <div
              key={idx}
              className="p-4 rounded-2xl border-2 border-brand-purple/20 bg-purple-50/30 flex flex-col justify-between space-y-3"
            >
              <div>
                <div className="flex items-center justify-between">
                  <span className="px-2.5 py-0.5 rounded-full text-xs font-black bg-brand-yellow text-brand-purple border border-brand-purple/20">
                    Hotspot #{idx + 1}
                  </span>
                  <span className="text-xs font-bold text-gray-700">Score: {hs.score}/100</span>
                </div>
                <div className="text-xs font-bold text-gray-900 mt-2">Grid Cell #{hs.cell_id}</div>
                <p className="text-xs text-gray-600 mt-1 leading-relaxed">{hs.reason}</p>
              </div>

              <button
                onClick={() => onAssignScouting && onAssignScouting(hs)}
                className="w-full py-2 bg-brand-purple hover:bg-brand-purple-dark text-brand-yellow font-bold text-xs rounded-xl shadow-sm transition flex items-center justify-center space-x-1.5"
              >
                <span>Assign Scouting</span>
                <ArrowRight className="w-3.5 h-3.5" />
              </button>
            </div>
          ))}
        </div>
      </div>

      {/* Data Used Footer */}
      <div className="bg-slate-100 rounded-2xl p-5 border border-gray-200 text-xs text-gray-600 space-y-2">
        <div className="flex items-center space-x-1.5 font-bold text-gray-800">
          <Database className="w-4 h-4 text-brand-purple" />
          <span>Data Sources Used & Audit Timestamp</span>
        </div>
        <p className="text-[11px] text-gray-500">
          All evaluations are reproducible and computed using snapshots stored in PostGIS.
        </p>
        <div className="flex flex-wrap gap-2 pt-1">
          {dataVersions.map((dv, idx) => (
            <span
              key={idx}
              className="px-2.5 py-1 rounded-lg bg-white border border-gray-200 text-[11px] font-medium text-gray-700"
            >
              <span className="font-semibold text-brand-purple">{dv.source}</span> ({dv.record_count} records)
            </span>
          ))}
        </div>
      </div>
    </div>
  );
}
